### ISSUE TITLE
db.dat Error

### ISSUE THREAD

**Issue by aesoruk** [tradle/react-native-regula-document-reader#1]
Hi,
db.dat is absent how do i solve

**Comment by aesoruk** [comment]
db.dat solved.

Error: Attempt to invoke virtual method 'java.lang.String com.regula.core.NativeWrapper.Process(android.content.Context, int, byte[], java.lang.String)' on a null object reference

**Comment by mvayngrib** [comment]
can you stop on this [line](https://github.com/tradle/react-native-regula-document-reader/blob/master/android/src/main/java/com/regula/documentreader/RNRegulaDocumentReaderModule.java#L77) and see maybe there are clues as to why one of the parameters is null?

**Comment by aesoruk** [comment]
let me see again parameters are not null
Unable to load module one not npm not install react-native-regula-document-reader can you check

**Comment by mvayngrib** [comment]
i don't know what you mean

**Comment by aesoruk** [comment]
npm ERR! code E404
npm ERR! 404 Not Found: react-native-regula-document-reader@latest

**Comment by mvayngrib** [comment]
i see what u mean, we never published this module to npm. I published it now, so u can give it a try. In the future, this is how you can install directly from the github repo: 

```
npm install -S https://github.com/tradle/react-native-regula-document-reader
```
